server:
  port: 8084

spring:
  application:
    name: wanwu-service-agent

dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
    register-mode: ${DUBBO_REGISTER_MODE:instance}
  protocol:
    name: dubbo
    port: 20884
  registry:
    address: ${DUBBO_REGISTRY_ADDRESS:N/A}
  consumer:
    check: false
    timeout: 5000
  provider:
    timeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: health,info
