CREATE TABLE IF NOT EXISTS api_key_statistics (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  org_id VARCHAR(64) NOT NULL,
  user_id VARCHAR(64) NOT NULL,
  api_key_id VARCHAR(64) NOT NULL,
  method_path VARCHAR(256) NOT NULL,
  date VARCHAR(16) NOT NULL,
  call_count BIGINT NOT NULL DEFAULT 0,
  call_failure BIGINT NOT NULL DEFAULT 0,
  stream_count BIGINT NOT NULL DEFAULT 0,
  non_stream_count BIGINT NOT NULL DEFAULT 0,
  stream_failure BIGINT NOT NULL DEFAULT 0,
  non_stream_failure BIGINT NOT NULL DEFAULT 0,
  stream_costs BIGINT NOT NULL DEFAULT 0,
  non_stream_costs BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_api_key_statistics_day (org_id, user_id, api_key_id, method_path, date),
  KEY idx_api_key_statistics_date (date),
  KEY idx_api_key_statistics_call_count (call_count),
  KEY idx_api_key_statistics_filter (user_id, org_id, date, api_key_id, method_path)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS api_key_records (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  org_id VARCHAR(64) NOT NULL,
  user_id VARCHAR(64) NOT NULL,
  api_key_id VARCHAR(64) NOT NULL,
  method_path VARCHAR(256) NOT NULL,
  call_time BIGINT NOT NULL,
  response_status VARCHAR(32) NOT NULL,
  is_stream TINYINT(1) NOT NULL DEFAULT 0,
  stream_costs BIGINT NOT NULL DEFAULT 0,
  non_stream_costs BIGINT NOT NULL DEFAULT 0,
  request_body LONGTEXT NULL,
  response_body LONGTEXT NULL,
  date VARCHAR(16) NOT NULL,
  PRIMARY KEY (id),
  KEY idx_api_key_records_filter (user_id, org_id, date, api_key_id, method_path),
  KEY idx_api_key_records_call_time (call_time),
  KEY idx_api_key_records_status (response_status),
  KEY idx_api_key_records_stream (is_stream)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
