CREATE TABLE IF NOT EXISTS app_statistics (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  org_id VARCHAR(64) NOT NULL,
  user_id VARCHAR(64) NOT NULL,
  app_id VARCHAR(64) NOT NULL,
  app_type VARCHAR(64) NOT NULL,
  date VARCHAR(16) NOT NULL,
  call_count BIGINT NOT NULL DEFAULT 0,
  call_failure BIGINT NOT NULL DEFAULT 0,
  stream_count BIGINT NOT NULL DEFAULT 0,
  stream_failure BIGINT NOT NULL DEFAULT 0,
  stream_costs BIGINT NOT NULL DEFAULT 0,
  non_stream_count BIGINT NOT NULL DEFAULT 0,
  non_stream_failure BIGINT NOT NULL DEFAULT 0,
  non_stream_costs BIGINT NOT NULL DEFAULT 0,
  web_call_count BIGINT NOT NULL DEFAULT 0,
  web_call_failure BIGINT NOT NULL DEFAULT 0,
  openapi_call_count BIGINT NOT NULL DEFAULT 0,
  openapi_call_failure BIGINT NOT NULL DEFAULT 0,
  web_url_call_count BIGINT NOT NULL DEFAULT 0,
  web_url_call_failure BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_app_statistics_day (org_id, user_id, app_id, app_type, date),
  KEY idx_app_statistics_date (date),
  KEY idx_app_statistics_call_count (call_count),
  KEY idx_app_statistics_filter (user_id, org_id, date, app_type, app_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS model_statistics (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  org_id VARCHAR(64) NOT NULL,
  user_id VARCHAR(64) NOT NULL,
  model_id VARCHAR(64) NOT NULL,
  provider VARCHAR(64) NOT NULL,
  date VARCHAR(16) NOT NULL,
  model VARCHAR(128) NOT NULL,
  model_type VARCHAR(32) NOT NULL,
  prompt_tokens BIGINT NOT NULL DEFAULT 0,
  completion_tokens BIGINT NOT NULL DEFAULT 0,
  total_tokens BIGINT NOT NULL DEFAULT 0,
  first_token_latency BIGINT NOT NULL DEFAULT 0,
  costs BIGINT NOT NULL DEFAULT 0,
  call_count BIGINT NOT NULL DEFAULT 0,
  stream_count BIGINT NOT NULL DEFAULT 0,
  non_stream_count BIGINT NOT NULL DEFAULT 0,
  call_failure BIGINT NOT NULL DEFAULT 0,
  stream_failure BIGINT NOT NULL DEFAULT 0,
  non_stream_failure BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_model_statistics_day (org_id, user_id, model_id, provider, date),
  KEY idx_model_statistics_date (date),
  KEY idx_model_statistics_model_type (model_type),
  KEY idx_model_statistics_call_count (call_count),
  KEY idx_model_statistics_filter (user_id, org_id, date, model_type, model_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
