CREATE TABLE IF NOT EXISTS app_templates (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  template_type VARCHAR(32) NOT NULL,
  template_id VARCHAR(96) NOT NULL,
  category VARCHAR(64) NOT NULL DEFAULT '',
  name VARCHAR(128) NOT NULL,
  description TEXT NULL,
  avatar_json JSON NULL,
  author VARCHAR(128) NOT NULL DEFAULT '',
  download_count INT NOT NULL DEFAULT 0,
  summary TEXT NULL,
  feature TEXT NULL,
  scenario TEXT NULL,
  note TEXT NULL,
  prologue TEXT NULL,
  instructions TEXT NULL,
  recommend_questions_json JSON NULL,
  workflow_instruction TEXT NULL,
  schema_json JSON NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_app_template_type_id (template_type, template_id),
  KEY idx_app_template_type_category (template_type, category),
  KEY idx_app_template_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

INSERT INTO app_templates (
  created_at, updated_at, template_type, template_id, category, name, description,
  avatar_json, author, download_count, summary, feature, scenario, note,
  prologue, instructions, recommend_questions_json, workflow_instruction, schema_json
) VALUES
(1700000000000, 1700000000000, 'assistant', 'assistant-template-policy', 'industry', 'Policy Analyst',
 'Summarize policy documents and produce action lists.',
 '{"key":"","path":""}', 'Wanwu Java', 0,
 'Summarize policy documents and produce action lists.',
 'Structured output, follow-up questions, and concise summaries.',
 'For policy, research, and compliance teams.', NULL,
 'I can help read policy documents.', 'You are a precise policy analysis assistant.',
 '["What is the goal?","What constraints matter?"]',
 'Optional workflow tools can be added after creation.', NULL),
(1700000000000, 1700000000000, 'assistant', 'assistant-template-learning', 'edu', 'Learning Coach',
 'Create learning plans and quizzes from a topic.',
 '{"key":"","path":""}', 'Wanwu Java', 0,
 'Create learning plans and quizzes from a topic.',
 'Structured output, follow-up questions, and concise summaries.',
 'For education and training scenarios.', NULL,
 'Tell me what you want to learn.', 'You are a patient learning coach.',
 '["What is the goal?","What constraints matter?"]',
 'Optional workflow tools can be added after creation.', NULL),
(1700000000000, 1700000000000, 'assistant', 'assistant-template-support', 'industry', 'Support Assistant',
 'Classify customer issues and draft replies.',
 '{"key":"","path":""}', 'Wanwu Java', 0,
 'Classify customer issues and draft replies.',
 'Structured output, follow-up questions, and concise summaries.',
 'For customer service teams.', NULL,
 'Describe the customer issue.', 'You are a calm customer support assistant.',
 '["What is the goal?","What constraints matter?"]',
 'Optional workflow tools can be added after creation.', NULL),
(1700000000000, 1700000000000, 'workflow', 'workflow-template-doc-review', 'office', 'Document Review',
 'Extract risks, owners, and next actions from a document.',
 '{"key":"","path":""}', 'Wanwu Java', 0,
 'Review uploaded documents and return a structured checklist.',
 'Local Java development template with deterministic schema.',
 'Use it to create a workflow draft and continue editing in App Space.',
 'The runtime workflow engine is still a local compatibility shell.',
 NULL, NULL, NULL, NULL,
 '{"id":"workflow-template-doc-review","name":"Document Review","desc":"Extract risks, owners, and next actions from a document.","nodes":[],"edges":[]}'),
(1700000000000, 1700000000000, 'workflow', 'workflow-template-faq', 'service', 'FAQ Generator',
 'Generate question-answer pairs from product notes.',
 '{"key":"","path":""}', 'Wanwu Java', 0,
 'Turn product or help-center material into FAQ content.',
 'Local Java development template with deterministic schema.',
 'Use it to create a workflow draft and continue editing in App Space.',
 'The runtime workflow engine is still a local compatibility shell.',
 NULL, NULL, NULL, NULL,
 '{"id":"workflow-template-faq","name":"FAQ Generator","desc":"Generate question-answer pairs from product notes.","nodes":[],"edges":[]}'),
(1700000000000, 1700000000000, 'workflow', 'workflow-template-brief', 'research', 'Research Brief',
 'Collect inputs and create a concise research brief.',
 '{"key":"","path":""}', 'Wanwu Java', 0,
 'Use this template for market, product, or policy research.',
 'Local Java development template with deterministic schema.',
 'Use it to create a workflow draft and continue editing in App Space.',
 'The runtime workflow engine is still a local compatibility shell.',
 NULL, NULL, NULL, NULL,
 '{"id":"workflow-template-brief","name":"Research Brief","desc":"Collect inputs and create a concise research brief.","nodes":[],"edges":[]}')
ON DUPLICATE KEY UPDATE updated_at = VALUES(updated_at);
