CREATE TABLE IF NOT EXISTS app_urls (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  user_id VARCHAR(64) NOT NULL,
  org_id VARCHAR(64) NOT NULL,
  app_id VARCHAR(64) NOT NULL,
  app_type VARCHAR(32) NOT NULL,
  name VARCHAR(128) NOT NULL,
  description TEXT NULL,
  expired_at BIGINT NOT NULL DEFAULT 0,
  copyright TEXT NULL,
  copyright_enable TINYINT(1) NOT NULL DEFAULT 0,
  privacy_policy TEXT NULL,
  privacy_policy_enable TINYINT(1) NOT NULL DEFAULT 0,
  disclaimer TEXT NULL,
  disclaimer_enable TINYINT(1) NOT NULL DEFAULT 0,
  suffix VARCHAR(128) NOT NULL,
  status TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (id),
  UNIQUE KEY uk_app_url_suffix (suffix),
  UNIQUE KEY uk_app_url_name (user_id, org_id, app_id, app_type, name),
  KEY idx_app_url_app (user_id, org_id, app_id, app_type),
  KEY idx_app_url_status (status),
  KEY idx_app_url_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
